import { Router, type IRouter } from "express";
import { healthRouter } from "./health.js";
import { authRouter } from "./auth.js";
import { porterRouter } from "./porter.js";
import { metricsRouter } from "./metrics.js";
import { jarvisRouter } from "./jarvis.js";
import { pnlRouter } from "./pnl.js";
import { commissionRouter } from "./commission.js";
import { settingsRouter } from "./settings.js";
import { artistsRouter } from "./artists.js";
import { customersRouter } from "./customers.js";
import { nudgesRouter } from "./nudges.js";
import { briefingRouter } from "./briefing.js";
import { appointmentsRouter } from "./appointments.js";
import { manualRouter } from "./manual.js";
import { importRouter } from "./import.js";
import { sopsRouter } from "./sops.js";
import { checklistRouter } from "./checklist.js";
import { devRouter } from "./dev.js";
import { tasksRouter } from "./tasks.js";
import { incidentsRouter } from "./incidents.js";
import { strategicNotesRouter } from "./strategicNotes.js";
import { filesRouter } from "./files.js";
import { inventoryRouter } from "./inventory.js";
import { teamMembersRouter } from "./teamMembers.js";
import { sopHistoryRouter } from "./sopHistory.js";
import { extraTasksRouter } from "./extraTasks.js";
import { searchRouter } from "./search.js";
import { quickbooksRouter } from "./quickbooks.js";
import { followupsRouter } from "./followups.js";

export const apiRouter: IRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/porter", porterRouter);
apiRouter.use("/metrics", metricsRouter);
apiRouter.use("/jarvis", jarvisRouter);
apiRouter.use("/brain-dump", jarvisRouter);
apiRouter.use("/pnl", pnlRouter);
apiRouter.use("/commissions", commissionRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/artists", artistsRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/nudges", nudgesRouter);
apiRouter.use("/briefing", briefingRouter);
apiRouter.use("/appointments", appointmentsRouter);
apiRouter.use("/manual", manualRouter);
apiRouter.use("/import", importRouter);
apiRouter.use("/sops", sopsRouter);
apiRouter.use("/checklist", checklistRouter);
apiRouter.use("/dev", devRouter);
apiRouter.use("/tasks", tasksRouter);
apiRouter.use("/incidents", incidentsRouter);
apiRouter.use("/strategic-notes", strategicNotesRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/team-members", teamMembersRouter);
apiRouter.use("/sop-history", sopHistoryRouter);
apiRouter.use("/extra-tasks", extraTasksRouter);
apiRouter.use("/files", filesRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/quickbooks", quickbooksRouter);
apiRouter.use("/followups", followupsRouter);
